import { getAppUrl } from "@carbon/auth";
import { getCarbonServiceRole } from "@carbon/auth/client.server";
import { ProofApprovalEmail } from "@carbon/documents/email";
import { logger, schemaTask } from "@trigger.dev/sdk";
import { renderAsync } from "@react-email/components";
import { z } from "zod";
import { copyToHotFolder } from "./hot-folder";
import { modelThumbnailTask } from "./model-thumbnail";
import { pdfFixupTask } from "./pdf-toolbox/fixup";
import { sendEmailResendTask } from "./send-email-resend";

/**
 * Builds the routing context JSON that gets passed to .kfpx flows.
 * This lets process plans make decisions based on downstream machines,
 * materials, quantities, etc.
 */
function buildPipelineContext(
  job: { id: string; jobId: string; quantity: number | null },
  operations: PipelineOperation[],
  currentIndex: number,
  materials: Array<{ name: string; itemId: string | null }>
): Record<string, unknown> {
  const current = operations[currentIndex];
  return {
    job: {
      id: job.id,
      jobId: job.jobId,
      quantity: job.quantity,
    },
    currentOperation: {
      id: current.id,
      process: current.processName,
      workCenter: current.workCenterName,
      order: current.order,
    },
    downstream: operations.slice(currentIndex + 1).map((op) => ({
      id: op.id,
      process: op.processName,
      workCenter: op.workCenterName,
      order: op.order,
    })),
    upstream: operations.slice(0, currentIndex).map((op) => ({
      id: op.id,
      process: op.processName,
      workCenter: op.workCenterName,
      order: op.order,
    })),
    materials,
  };
}

interface PipelineOperation {
  id: string;
  order: number;
  operationOrder: string | null;
  processId: string;
  workCenterId: string | null;
  processName: string;
  processPlanPath: string;
  outputDestination: string;
  workCenterName: string | null;
  hotFolderPath: string | null;
  modelUploadId: string | null;
  modelUploadModelPath: string | null;
}

/**
 * Auto-sends proof approval email to customer contacts when a proof is
 * generated by the pipeline. Follows the same contact resolution logic
 * as the manual proof flow ($jobId.proof.tsx).
 */
async function sendProofEmail(
  client: ReturnType<typeof getCarbonServiceRole>,
  params: {
    jobId: string;
    companyId: string;
    userId: string;
    externalLinkId: string;
    version: number;
  }
): Promise<void> {
  const { jobId, companyId, userId, externalLinkId, version } = params;

  // Get job details
  const { data: job } = await client
    .from("job")
    .select("name, salesOrderId, customerId")
    .eq("id", jobId)
    .single();

  if (!job?.salesOrderId) {
    logger.info("No sales order on job, skipping proof email", { jobId });
    return;
  }

  // Resolve customer contacts via sales order
  const { data: salesOrder } = await client
    .from("salesOrder")
    .select("customerContactId, customerId")
    .eq("id", job.salesOrderId)
    .single();

  const emailAddresses: string[] = [];
  let recipientFirstName: string | undefined;

  // Get SO contact email
  if (salesOrder?.customerContactId) {
    const { data: customerContact } = await client
      .from("customerContact")
      .select("contact(firstName, email)")
      .eq("id", salesOrder.customerContactId)
      .single();

    const contact = customerContact?.contact as {
      firstName: string | null;
      email: string | null;
    } | null;
    if (contact?.email) {
      emailAddresses.push(contact.email);
      recipientFirstName = contact.firstName ?? undefined;
    }
  }

  // Get customer's sales contact (if different from SO contact)
  const customerId = salesOrder?.customerId ?? job.customerId;
  if (customerId) {
    const { data: customer } = await client
      .from("customer")
      .select("salesContactId")
      .eq("id", customerId)
      .single();

    if (
      customer?.salesContactId &&
      customer.salesContactId !== salesOrder?.customerContactId
    ) {
      const { data: salesContact } = await client
        .from("customerContact")
        .select("contact(email)")
        .eq("id", customer.salesContactId)
        .single();

      const contact = salesContact?.contact as {
        email: string | null;
      } | null;
      if (contact?.email) {
        emailAddresses.push(contact.email);
      }
    }
  }

  if (emailAddresses.length === 0) {
    logger.info("No customer contact emails found, skipping proof email", {
      jobId,
    });
    return;
  }

  // Get company and user info for email template
  const [{ data: company }, { data: user }] = await Promise.all([
    client.from("companies").select("*").eq("id", companyId).single(),
    client
      .from("user")
      .select("email, firstName, lastName")
      .eq("id", userId)
      .single(),
  ]);

  if (!company || !user) {
    logger.warn("Missing company or user data for proof email", {
      companyId,
      userId,
    });
    return;
  }

  const proofUrl = `${getAppUrl()}/share/proof/${externalLinkId}`;
  const jobName = job.name ?? "Job";

  const emailTemplate = ProofApprovalEmail({
    company,
    jobName,
    proofUrl,
    version,
    recipient: {
      firstName: recipientFirstName,
      email: emailAddresses[0],
    },
    sender: {
      email: user.email,
      firstName: user.firstName,
      lastName: user.lastName,
    },
    locale: "en-US",
  });

  const html = await renderAsync(emailTemplate);
  const text = await renderAsync(emailTemplate, { plainText: true });

  const uniqueEmails = Array.from(new Set(emailAddresses));

  await sendEmailResendTask.trigger({
    to: uniqueEmails,
    subject: `Proof Approval — ${jobName}`,
    html,
    text,
    companyId,
  });

  logger.info(`Sent proof approval email to ${uniqueEmails.join(", ")}`, {
    jobId,
  });
}

export const generateSubProductionFilesTask = schemaTask({
  id: "generate-sub-production-files",
  schema: z.object({
    jobId: z.string(),
    companyId: z.string(),
    userId: z.string(),
    /** "create" = runOnCreate operations only, "release" = remaining operations */
    phase: z.enum(["create", "release"]).default("release"),
  }),
  run: async (payload) => {
    const { jobId, companyId, userId, phase } = payload;
    const client = getCarbonServiceRole();

    // Resolve the master file from the job's item
    const { data: job, error: jobError } = await client
      .from("job")
      .select("id, jobId, quantity, itemId, item!inner(modelUploadId)")
      .eq("id", jobId)
      .single();

    if (jobError || !job) {
      throw new Error(
        `Failed to look up job: ${jobError?.message ?? "no data"}`
      );
    }

    const item = job.item as { modelUploadId: string | null };
    const masterModelUploadId = item.modelUploadId;

    if (!masterModelUploadId) {
      logger.info("No master file on item, skipping pipeline", { jobId });
      return { generated: 0 };
    }

    // Get the master file path
    const { data: masterUpload, error: masterError } = await client
      .from("modelUpload")
      .select("modelPath, name")
      .eq("id", masterModelUploadId)
      .single();

    if (masterError || !masterUpload?.modelPath) {
      throw new Error(
        `Failed to look up master file: ${masterError?.message ?? "no data"}`
      );
    }

    const masterModelPath = masterUpload.modelPath;

    // Get ALL job operations with process plans, ordered by sequence.
    // We need all of them to build context, but only process the ones
    // matching our phase filter.
    const { data: allOperations, error: opsError } = await client
      .from("jobOperation")
      .select(
        `id, order, operationOrder, processId, workCenterId, modelUploadId,
         process!inner(id, name, processPlanPath, runOnCreate, outputDestination),
         workCenter(id, name)`
      )
      .eq("jobId", jobId)
      .not("process.processPlanPath", "is", null)
      .order("order");

    if (opsError) {
      throw new Error(
        `Failed to look up job operations: ${opsError.message}`
      );
    }

    if (!allOperations?.length) {
      logger.info("No operations with process plans configured, skipping", {
        jobId,
      });
      return { generated: 0 };
    }

    // Fetch hot folder paths for work center + process pairings
    const wcProcessPairs = allOperations
      .filter((op) => op.workCenterId && op.processId)
      .map((op) => ({ workCenterId: op.workCenterId!, processId: op.processId }));

    const hotFolderMap = new Map<string, string>();
    if (wcProcessPairs.length > 0) {
      const { data: wcProcesses } = await client
        .from("workCenterProcess")
        .select("workCenterId, processId, hotFolderPath")
        .in(
          "workCenterId",
          wcProcessPairs.map((p) => p.workCenterId)
        )
        .in(
          "processId",
          wcProcessPairs.map((p) => p.processId)
        );

      if (wcProcesses) {
        for (const wcp of wcProcesses) {
          if (wcp.hotFolderPath) {
            hotFolderMap.set(
              `${wcp.workCenterId}:${wcp.processId}`,
              wcp.hotFolderPath
            );
          }
        }
      }
    }

    // Flatten operations into pipeline format
    const pipelineOps: PipelineOperation[] = allOperations.map((op) => {
      const process = op.process as {
        id: string;
        name: string;
        processPlanPath: string;
        runOnCreate: boolean;
        outputDestination: string;
      };
      const workCenter = op.workCenter as { id: string; name: string } | null;
      const hotFolderKey = op.workCenterId && op.processId
        ? `${op.workCenterId}:${op.processId}`
        : null;

      return {
        id: op.id,
        order: op.order ?? 0,
        operationOrder: op.operationOrder,
        processId: op.processId!,
        workCenterId: op.workCenterId,
        processName: process.name,
        processPlanPath: process.processPlanPath,
        outputDestination: process.outputDestination,
        runOnCreate: process.runOnCreate,
        workCenterName: workCenter?.name ?? null,
        hotFolderPath: hotFolderKey ? hotFolderMap.get(hotFolderKey) ?? null : null,
        modelUploadId: op.modelUploadId,
        modelUploadModelPath: null, // Resolved below for already-processed ops
      } as PipelineOperation & { runOnCreate: boolean };
    });

    // For operations that already have output, resolve their file paths
    // (needed for threading already-processed output forward)
    const processedOps = pipelineOps.filter((op) => op.modelUploadId);
    if (processedOps.length > 0) {
      const { data: existingUploads } = await client
        .from("modelUpload")
        .select("id, modelPath")
        .in(
          "id",
          processedOps.map((op) => op.modelUploadId!)
        );

      if (existingUploads) {
        const uploadMap = new Map(
          existingUploads.map((u) => [u.id, u.modelPath as string | null])
        );
        for (const op of pipelineOps) {
          if (op.modelUploadId) {
            op.modelUploadModelPath = uploadMap.get(op.modelUploadId) ?? null;
          }
        }
      }
    }

    // Get job materials for context
    const { data: materials } = await client
      .from("jobMaterial")
      .select("item(name)")
      .eq("jobId", jobId);

    const materialsList = (materials ?? []).map((m) => ({
      name: (m.item as { name: string } | null)?.name ?? "Unknown",
      itemId: null,
    }));

    // Filter operations by phase
    const phaseFilteredOps = pipelineOps.filter((op) => {
      const opWithPhase = op as PipelineOperation & { runOnCreate: boolean };
      return phase === "create" ? opWithPhase.runOnCreate : !opWithPhase.runOnCreate;
    });

    if (!phaseFilteredOps.length) {
      logger.info(`No operations to process for phase "${phase}"`, { jobId });
      return { generated: 0 };
    }

    logger.info(
      `Processing ${phaseFilteredOps.length} operations (phase: ${phase})`,
      { jobId }
    );

    // Sequential pipeline with output threading
    let previousOutputPath = masterModelPath;
    let lastAfterPreviousInput = masterModelPath;
    let generated = 0;

    // Walk through ALL operations in order to maintain pipeline threading,
    // but only execute process plans for phase-matching operations.
    for (let i = 0; i < pipelineOps.length; i++) {
      const operation = pipelineOps[i];
      const opWithPhase = operation as PipelineOperation & { runOnCreate: boolean };
      const isPhaseMatch =
        phase === "create" ? opWithPhase.runOnCreate : !opWithPhase.runOnCreate;

      // Determine this operation's input based on pipeline position
      const inputPath =
        operation.operationOrder === "With Previous"
          ? lastAfterPreviousInput
          : previousOutputPath;

      if (!isPhaseMatch) {
        // Not our phase — but still thread output forward if already processed
        if (operation.modelUploadModelPath && operation.operationOrder !== "With Previous") {
          previousOutputPath = operation.modelUploadModelPath;
          lastAfterPreviousInput = inputPath;
        }
        continue;
      }

      // Skip if already processed (idempotency)
      if (operation.modelUploadId && operation.modelUploadModelPath) {
        logger.info(`Operation ${operation.id} already processed, skipping`, {
          process: operation.processName,
        });
        if (operation.operationOrder !== "With Previous") {
          previousOutputPath = operation.modelUploadModelPath;
          lastAfterPreviousInput = inputPath;
        }
        continue;
      }

      try {
        logger.info(`Processing operation ${operation.id}`, {
          process: operation.processName,
          processPlan: operation.processPlanPath,
          outputDestination: operation.outputDestination,
        });

        const outputDir = `${companyId}/models/sub-production/${jobId}/${operation.id}`;
        const outputFileName = `${operation.id}.pdf`;

        // Build routing context for this operation
        const context = buildPipelineContext(
          { id: job.id, jobId: job.jobId!, quantity: job.quantity },
          pipelineOps,
          i,
          materialsList
        );

        // Execute the process plan via pdfToolbox
        const result = await pdfFixupTask
          .triggerAndWait({
            companyId,
            inputPath,
            outputDir,
            processPlan: operation.processPlanPath,
            outputFileName,
            masterPath: masterModelPath,
            context,
          })
          .unwrap();

        // Route output based on destination
        switch (operation.outputDestination) {
          case "proof": {
            // Create a modelUpload record for the proof file
            const proofModelId = `proof_${operation.id}`;
            await client.from("modelUpload").upsert({
              id: proofModelId,
              name: `Proof - ${masterUpload.name}`,
              modelPath: result.outputPath,
              size: 0,
              companyId,
              createdBy: userId,
            });

            // Find or create external link for proof sharing
            const { data: existingLink } = await client
              .from("externalLink")
              .select("id")
              .eq("documentType", "ProofApproval")
              .eq("documentId", jobId)
              .eq("companyId", companyId)
              .maybeSingle();

            let externalLinkId = existingLink?.id;
            if (!externalLinkId) {
              const { data: newLink } = await client
                .from("externalLink")
                .insert({
                  companyId,
                  documentType: "ProofApproval",
                  documentId: jobId,
                })
                .select("id")
                .single();
              externalLinkId = newLink?.id;
            }

            // Supersede existing pending proofs
            await client
              .from("proofApproval")
              .update({ status: "Superseded" })
              .eq("jobId", jobId)
              .eq("status", "Pending");

            // Get next version
            const { data: existingProofs } = await client
              .from("proofApproval")
              .select("version")
              .eq("jobId", jobId)
              .order("version", { ascending: false })
              .limit(1);

            const nextVersion =
              existingProofs?.length ? existingProofs[0].version + 1 : 1;

            // Create proof approval record
            await client.from("proofApproval").insert({
              jobId,
              companyId,
              requestedBy: userId,
              modelUploadId: proofModelId,
              version: nextVersion,
              externalLinkId: externalLinkId ?? undefined,
            });

            // Update job status to Awaiting Proof Approval
            await client
              .from("job")
              .update({ status: "Awaiting Proof Approval", proofSkipped: false })
              .eq("id", jobId);

            // Generate thumbnail for the proof
            await modelThumbnailTask.trigger({
              companyId,
              modelId: proofModelId,
            });

            // Auto-send proof approval email to customer contacts
            if (externalLinkId) {
              try {
                await sendProofEmail(client, {
                  jobId,
                  companyId,
                  userId,
                  externalLinkId,
                  version: nextVersion,
                });
              } catch (emailErr) {
                logger.warn("Failed to send proof email (non-fatal)", {
                  error: emailErr instanceof Error ? emailErr.message : String(emailErr),
                });
              }
            }

            logger.info(`Created proof approval for operation ${operation.id}`);
            break;
          }

          case "master": {
            // Create a new modelUpload for the normalized master
            const normalizedModelId = `norm_${operation.id}`;
            await client.from("modelUpload").upsert({
              id: normalizedModelId,
              name: `Normalized - ${masterUpload.name}`,
              modelPath: result.outputPath,
              size: 0,
              companyId,
              createdBy: userId,
            });

            // Update the item's master file (permanent change)
            const { data: jobForItem } = await client
              .from("job")
              .select("itemId")
              .eq("id", jobId)
              .single();

            if (jobForItem?.itemId) {
              await client
                .from("item")
                .update({ modelUploadId: normalizedModelId })
                .eq("id", jobForItem.itemId);

              logger.info(
                `Updated item master file for item ${jobForItem.itemId}`
              );
            }

            // Generate thumbnail for the normalized file
            await modelThumbnailTask.trigger({
              companyId,
              modelId: normalizedModelId,
            });
            break;
          }

          case "operation":
          default: {
            // Standard: link output to jobOperation (existing behavior)
            const subModelId = `sub_${operation.id}`;
            const { error: insertError } = await client
              .from("modelUpload")
              .upsert({
                id: subModelId,
                name: `${operation.processName} - ${masterUpload.name}`,
                modelPath: result.outputPath,
                size: 0,
                companyId,
                createdBy: userId,
              });

            if (insertError) {
              logger.error(
                `Failed to create modelUpload for operation ${operation.id}`,
                { error: insertError.message }
              );
              continue;
            }

            const { error: updateError } = await client
              .from("jobOperation")
              .update({ modelUploadId: subModelId })
              .eq("id", operation.id);

            if (updateError) {
              logger.error(
                `Failed to update jobOperation ${operation.id}`,
                { error: updateError.message }
              );
              continue;
            }

            // Generate thumbnail
            await modelThumbnailTask.trigger({
              companyId,
              modelId: subModelId,
            });
            break;
          }
        }

        // Hot folder routing
        if (operation.hotFolderPath) {
          try {
            const { data: outputFile } = await client.storage
              .from("private")
              .download(result.outputPath);

            if (outputFile) {
              const arrayBuffer = await outputFile.arrayBuffer();
              const safeName = (job.jobId ?? jobId).replace(/[^a-zA-Z0-9-_]/g, "_");
              const safeProcess = operation.processName.replace(/[^a-zA-Z0-9-_]/g, "_");

              await copyToHotFolder({
                hotFolderPath: operation.hotFolderPath,
                fileName: `${safeName}_${safeProcess}.pdf`,
                fileBuffer: arrayBuffer,
              });
            }
          } catch (hotFolderErr) {
            logger.warn(
              `Hot folder copy failed for operation ${operation.id}`,
              {
                error:
                  hotFolderErr instanceof Error
                    ? hotFolderErr.message
                    : String(hotFolderErr),
              }
            );
          }
        }

        // Thread output forward for "After Previous" operations
        if (operation.operationOrder !== "With Previous") {
          previousOutputPath = result.outputPath;
          lastAfterPreviousInput = inputPath;
        }

        generated++;
        logger.info(
          `Generated file for operation ${operation.id} (${operation.outputDestination})`
        );
      } catch (err) {
        logger.error(
          `Failed to process operation ${operation.id}`,
          { error: err instanceof Error ? err.message : String(err) }
        );
      }
    }

    logger.info(`Pipeline complete (phase: ${phase})`, {
      jobId,
      generated,
      total: phaseFilteredOps.length,
    });

    return { generated, total: phaseFilteredOps.length };
  },
});
